<?php

namespace ContainerPxKbMD4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H769hySService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h769hyS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h769hyS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminController::ajoutannonce' => ['privates', '.service_locator.iEkTfmH', 'get_ServiceLocator_IEkTfmHService', true],
            'App\\Controller\\Admin\\AnnoncesController::activer' => ['privates', '.service_locator.3ALL0bJ', 'get_ServiceLocator_3ALL0bJService', true],
            'App\\Controller\\Admin\\AnnoncesController::index' => ['privates', '.service_locator.KB_aObY', 'get_ServiceLocator_KBAObYService', true],
            'App\\Controller\\Admin\\AnnoncesController::supprimer' => ['privates', '.service_locator.3ALL0bJ', 'get_ServiceLocator_3ALL0bJService', true],
            'App\\Controller\\Admin\\CategoriesController::ModifCategories' => ['privates', '.service_locator.16CYUIJ', 'get_ServiceLocator_16CYUIJService', true],
            'App\\Controller\\Admin\\CategoriesController::ajoutCategorie' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Admin\\CategoriesController::index' => ['privates', '.service_locator.XwAl1Ry', 'get_ServiceLocator_XwAl1RyService', true],
            'App\\Controller\\AnnoncesController::details' => ['privates', '.service_locator.T3sFFuj', 'get_ServiceLocator_T3sFFujService', true],
            'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.T3sFFuj', 'get_ServiceLocator_T3sFFujService', true],
            'App\\Controller\\HomeController::contact' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\InvoiceController::ajoutannonce' => ['privates', '.service_locator.9a9hyd6', 'get_ServiceLocator_9a9hyd6Service', true],
            'App\\Controller\\PanierController::add' => ['privates', '.service_locator.RGVpocl', 'get_ServiceLocator_RGVpoclService', true],
            'App\\Controller\\PanierController::less' => ['privates', '.service_locator.RGVpocl', 'get_ServiceLocator_RGVpoclService', true],
            'App\\Controller\\PanierController::remove' => ['privates', '.service_locator.RGVpocl', 'get_ServiceLocator_RGVpoclService', true],
            'App\\Controller\\PanierController::voir' => ['privates', '.service_locator.1GR2ivr', 'get_ServiceLocator_1GR2ivrService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.GMaAxnD', 'get_ServiceLocator_GMaAxnDService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\StripeController::checkout' => ['privates', '.service_locator.kvzU9KI', 'get_ServiceLocator_KvzU9KIService', true],
            'App\\Controller\\StripeController::error' => ['privates', '.service_locator._cqZQgy', 'get_ServiceLocator_CqZQgyService', true],
            'App\\Controller\\StripeController::success' => ['privates', '.service_locator.4mPaYOn', 'get_ServiceLocator_4mPaYOnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\AdminController:ajoutannonce' => ['privates', '.service_locator.iEkTfmH', 'get_ServiceLocator_IEkTfmHService', true],
            'App\\Controller\\Admin\\AnnoncesController:activer' => ['privates', '.service_locator.3ALL0bJ', 'get_ServiceLocator_3ALL0bJService', true],
            'App\\Controller\\Admin\\AnnoncesController:index' => ['privates', '.service_locator.KB_aObY', 'get_ServiceLocator_KBAObYService', true],
            'App\\Controller\\Admin\\AnnoncesController:supprimer' => ['privates', '.service_locator.3ALL0bJ', 'get_ServiceLocator_3ALL0bJService', true],
            'App\\Controller\\Admin\\CategoriesController:ModifCategories' => ['privates', '.service_locator.16CYUIJ', 'get_ServiceLocator_16CYUIJService', true],
            'App\\Controller\\Admin\\CategoriesController:ajoutCategorie' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Admin\\CategoriesController:index' => ['privates', '.service_locator.XwAl1Ry', 'get_ServiceLocator_XwAl1RyService', true],
            'App\\Controller\\AnnoncesController:details' => ['privates', '.service_locator.T3sFFuj', 'get_ServiceLocator_T3sFFujService', true],
            'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.T3sFFuj', 'get_ServiceLocator_T3sFFujService', true],
            'App\\Controller\\HomeController:contact' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\InvoiceController:ajoutannonce' => ['privates', '.service_locator.9a9hyd6', 'get_ServiceLocator_9a9hyd6Service', true],
            'App\\Controller\\PanierController:add' => ['privates', '.service_locator.RGVpocl', 'get_ServiceLocator_RGVpoclService', true],
            'App\\Controller\\PanierController:less' => ['privates', '.service_locator.RGVpocl', 'get_ServiceLocator_RGVpoclService', true],
            'App\\Controller\\PanierController:remove' => ['privates', '.service_locator.RGVpocl', 'get_ServiceLocator_RGVpoclService', true],
            'App\\Controller\\PanierController:voir' => ['privates', '.service_locator.1GR2ivr', 'get_ServiceLocator_1GR2ivrService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.GMaAxnD', 'get_ServiceLocator_GMaAxnDService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\StripeController:checkout' => ['privates', '.service_locator.kvzU9KI', 'get_ServiceLocator_KvzU9KIService', true],
            'App\\Controller\\StripeController:error' => ['privates', '.service_locator._cqZQgy', 'get_ServiceLocator_CqZQgyService', true],
            'App\\Controller\\StripeController:success' => ['privates', '.service_locator.4mPaYOn', 'get_ServiceLocator_4mPaYOnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\AdminController::ajoutannonce' => '?',
            'App\\Controller\\Admin\\AnnoncesController::activer' => '?',
            'App\\Controller\\Admin\\AnnoncesController::index' => '?',
            'App\\Controller\\Admin\\AnnoncesController::supprimer' => '?',
            'App\\Controller\\Admin\\CategoriesController::ModifCategories' => '?',
            'App\\Controller\\Admin\\CategoriesController::ajoutCategorie' => '?',
            'App\\Controller\\Admin\\CategoriesController::index' => '?',
            'App\\Controller\\AnnoncesController::details' => '?',
            'App\\Controller\\ArticlesController::index' => '?',
            'App\\Controller\\HomeController::contact' => '?',
            'App\\Controller\\InvoiceController::ajoutannonce' => '?',
            'App\\Controller\\PanierController::add' => '?',
            'App\\Controller\\PanierController::less' => '?',
            'App\\Controller\\PanierController::remove' => '?',
            'App\\Controller\\PanierController::voir' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StripeController::checkout' => '?',
            'App\\Controller\\StripeController::error' => '?',
            'App\\Controller\\StripeController::success' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminController:ajoutannonce' => '?',
            'App\\Controller\\Admin\\AnnoncesController:activer' => '?',
            'App\\Controller\\Admin\\AnnoncesController:index' => '?',
            'App\\Controller\\Admin\\AnnoncesController:supprimer' => '?',
            'App\\Controller\\Admin\\CategoriesController:ModifCategories' => '?',
            'App\\Controller\\Admin\\CategoriesController:ajoutCategorie' => '?',
            'App\\Controller\\Admin\\CategoriesController:index' => '?',
            'App\\Controller\\AnnoncesController:details' => '?',
            'App\\Controller\\ArticlesController:index' => '?',
            'App\\Controller\\HomeController:contact' => '?',
            'App\\Controller\\InvoiceController:ajoutannonce' => '?',
            'App\\Controller\\PanierController:add' => '?',
            'App\\Controller\\PanierController:less' => '?',
            'App\\Controller\\PanierController:remove' => '?',
            'App\\Controller\\PanierController:voir' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StripeController:checkout' => '?',
            'App\\Controller\\StripeController:error' => '?',
            'App\\Controller\\StripeController:success' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
