<?php

namespace ContainerPxKbMD4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RGVpoclService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RGVpocl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RGVpocl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.RGVpocl.App\\Entity\\Annonces', NULL, 'Cannot autowire service ".service_locator.RGVpocl": it references class "App\\Entity\\Annonces" but no such service exists.'],
        ], [
            'product' => 'App\\Entity\\Annonces',
        ]);
    }
}
