<?php

namespace ContainerPxKbMD4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoice3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kvzU9KI.App\Entity\Invoice' shared service.
     *
     * @return \App\Entity\Invoice
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kvzU9KI": it references class "App\\Entity\\Invoice" but no such service exists.');
    }
}
