<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW71wptx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW71wptx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW71wptx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW71wptx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW71wptx\App_KernelDevDebugContainer([
    'container.build_hash' => 'W71wptx',
    'container.build_id' => '43574366',
    'container.build_time' => 1665876862,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW71wptx');
