<?php

namespace ContainerW71wptx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3ALL0bJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3ALL0bJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3ALL0bJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'annonce' => ['privates', '.errored..service_locator.3ALL0bJ.App\\Entity\\Annonces', NULL, 'Cannot autowire service ".service_locator.3ALL0bJ": it references class "App\\Entity\\Annonces" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonce' => 'App\\Entity\\Annonces',
            'doctrine' => '?',
            'entityManager' => '?',
        ]);
    }
}
